name: Release
on:
    release:
        types: [created]
jobs:
    ci:
        name: CI Checks
        uses: ./.github/workflows/ci.yaml
    release:
        name: Publish
        needs: ci
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup npm authentication
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Publish
              run: npm publish --access=public --provenance
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
